### ISSUE TITLE
How to add a relation to a Resource.

### ISSUE THREAD

**Issue by EnricoVogt** [lagoshny/ngx-hateoas-client#105]
Hello im new to topic and wonder how to add a relation. Lets say i have the following Resource
```
{
        "name": "Job #1",
        "description": "test Job #1",
        "exportType": "CSV",
        "_links": {
          "self": {
            "href": "http://localhost:8080/jobs/2"
          },
          "database": {
            "href": "http://localhost:8080/jobs/2/database"
          },
        }
      },
```

Now, when i try to add a new resource, i have to pass a the URI of the associated Database in the POST Payload:

```
{
"name": "new",
"description": "new",
"exportType": "CSV",
"database": "Path to related databse object (in my case http://localhost:8080/databases/1)",
}

```

How this can be done with the Client? I have to add the Database field to my Job-Resource Object? For now it looks like this:
```

@HateoasResource('jobs')
export class JobConfig extends Resource {
    public name!: string;
    public description!: string;
    public exportType!: 'CSV' | 'XLS';
}

```

Thanks in advanved!

**Comment by lagoshny** [comment]
@EnricoVogt Hi,

You need to create a new `Resource` class for relation. And after that you can add this class as field to your main resource.

`````ts
@HateoasResource('databases')
export class Database extends Resource {
 ....
}

@HateoasResource('jobs')
export class JobConfig extends Resource {
    public name!: string;
    public description!: string;
    public exportType!: 'CSV' | 'XLS';
    // put new field with new resource type
    public database: Database;
}
`````

Now when you load from server `Database` resource and set it in `JobConfig` property it automatically will create JSON body as you want.

````json
{
"name": "new",
"description": "new",
"exportType": "CSV",
"database": "Path to related databse object (in my case http://localhost:8080/databases/1)",
}
````

The client will convert Database class to Database._links.self URL when you will create JobConfig .

**Comment by EnricoVogt** [comment]
@lagoshny Hi, thank you for your fast response. Its working like a charm. Thanks for providing and maintaining this library.

Also, is there a prefered way to get a relation? For now im doing it like this:
```
job.getRelation<Database>('database')
  .subscribe((db: Database) => {
    job.database = db
  });
```

I think method like "resolveRelations" would be handy which are doing this for all relations.

**Comment by lagoshny** [comment]
Yes, you get relation in right way.

Also, if you want to get object with loaded relations as simple objects, you can use projections. 
For backend side, you can see [here](https://www.baeldung.com/spring-data-rest-projections-excerpts).
And client side [here](https://github.com/lagoshny/ngx-hateoas-client#hateoasprojection)

About separate method `resolveRelations` it seems as good idea I will think about it, thank you.

**Comment by EnricoVogt** [comment]
Thank you for your helpful advice
