### ISSUE TITLE
No app.module in my angular application

### ISSUE THREAD

**Issue by gguptha** [lagoshny/ngx-hateoas-client#109]
Hi, we do not have app.module in our application and all out components are standalone. Can you let me know where to place the below code in this situation?

NgxHateoasClientModule configuration:
import { NgxHateoasClientModule } from '@lagoshny/ngx-hateoas-client';

...

```
@NgModule({
  ...
  imports: [
    HttpClientModule,
    ...
    NgxHateoasClientModule.forRoot()
    ...
  ]
  ...
})
export class AppModule {
  ...
}
```
In constructor app root module inject NgxHateoasClientConfigurationService and pass a configuration:
Minimal configuration look like this:

Using common URL to retrieve Resources
```
import { ..., NgxHateoasClientConfigurationService } from '@lagoshny/ngx-hateoas-client';

...

export class AppModule {

  constructor(hateoasConfig: NgxHateoasClientConfigurationService) {
    hateoasConfig.configure({
      http: {
        rootUrl: 'http://localhost:8080/api/v1'
      }
    });
  }

}
```

**Comment by lagoshny** [comment]
Hi @gguptha ,

It is not necessary to put this configuration in `AppModule` it is an example for most applications.
If your standalone module uses `NgxHateoas` libs then put configuration to this module.

If you have some problem with it, please provide a small example of your application structure where I can reproduce the problem.

**Comment by gguptha** [comment]
Hi @lagoshny ,

What I meant was that my angular app has no modules at all. They contain standalone components.

You can see my app here -
[https://github.com/gguptha/paperflow-bo](url)

Would be very helpful if you could let me know how to proceed in this case.

Thanks.

**Comment by lagoshny** [comment]
@gguptha,

The main things that `ngx-hateoas-lib` needs is injecting somewhere `NgxHateoasClientConfigurationService` and pass your configuration for this.

In your case, you should create new `core` component for this.
For example, under path `src/app/core/hateoas`  create two files:

`hateoas-configuration.service.ts`:
````ts
import { Injectable } from '@angular/core';
import { NgxHateoasClientConfigurationService } from '@lagoshny/ngx-hateoas-client';

@Injectable({providedIn: 'root'})
export class HateoasConfigurationService {

    constructor(config: NgxHateoasClientConfigurationService) {
        // put your configuration here
        config.configure({
            http: {
                rootUrl: "http://localhost:8080/api/v1"
            }
        })
    }

}
````

and the second one `hateoas.provider.ts`:

````ts
import { ENVIRONMENT_INITIALIZER, inject, Provider } from '@angular/core';
import { HateoasConfigurationService } from './hateoas-configuration.service';

export const provideHateoas = (): Provider =>
{
    return [
        {
            provide : ENVIRONMENT_INITIALIZER,
            useValue: () => inject(HateoasConfigurationService),
            multi   : true,
        },
    ];
};
````

After that, you can specify provideHateoas() in your `app.config.ts` file in provider section like other providers:

``````ts
export const appConfig: ApplicationConfig = {
    providers: [
       ....
       provideHateoas(),
       ....
    ]
};
``````

Now you can create `Resources` for your components and use `HateoasResourceService` or `HateoasResourceOperation<>` services to get your resources.

Also, if you want to override `hateoas-config` for some components, you can inject `NgxHateoasClientConfigurationService` directly to your component class and pass another configuration for this standalone component.

I hope this will help you, if you have more questions, don't hesitate to ask them.

**Comment by lagoshny** [comment]
No problem, I close the issue.
