### ISSUE TITLE
Creating Resources - Same Models For GET and POST/PUT Operations

### ISSUE THREAD

**Issue by mathias-ewald** [lagoshny/ngx-hateoas-client#113]
Hi, I have come to ditch Spring Data Rest and implement the API with Spring HATEOAS myself, which is why I am now confronted with many details, I haven't given too much thought when SDR did all the work :D  I came across the situation that my entity `Transition` has relation "project" to the `Project`entity, so a GET on a Transition yields the following response:

```
{
  ...
  "_links": {
    "self": {
      "href": "http://localhost:8080/transitions/demo1transition3",
    },
    "project": {
      "href": "http://localhost:8080/projects/project1"
    }
  }
}
```

What I know works in order to create a new `Transition` is this:

```
@HateoasResource('projects')
export class Project extends Resource { ... }

@HateoasResource('transitions')
export class Transition extends Resource {
    ...
    public project?: Project;
}
```
```
const t: Transition = new Transition();
t.project = project;

this.transitionService.createResource({ body: t }).subscribe();
```

The document that the library generates and sends to the API endpoint looks like this:

```
{
    "project": "http://localhost:8080/projects/project1"
}
```
So the href to the Project resource is posted in the "project" property as a string.

On the server-side, this forces me to have different models for read and write operations in order to map the "project" String so it can then be resolved to an actual entity.

Looking at the [spec](https://datatracker.ietf.org/doc/html/draft-kelly-json-hal), I am not reading about any suggestion / recommendation whatsoever that says "this is how it should work". On the contrary, I want to argue that using the same models for read and write operations is the much more obvious thing to do and we can resort to separate models as needed. 

So what I am looking for is a way with ngx-hateaos-client to use `_links` to express a relation during a POST/PUT or PATCH operation, but I was't able to figure out how.

**Comment by lagoshny** [comment]
Hi @mathias-ewald ,

I think there is not a simple answer.
Spec is in draft status and seems that will not be finished)

For Spring Data Rest you can use wrapper like `EntityModel<Transition> transitionResource` then Spring will do all work for you :) 

About Spring HATEOAS you can see these discussions about it [1](https://github.com/spring-projects/spring-hateoas/issues/774), [2](https://stackoverflow.com/questions/49458567/mapping-hal-uri-in-requestbody-to-a-spring-data-rest-managed-entity).

**Comment by mathias-ewald** [comment]
Ok, but my suggestion is to support it in the client library then :) Unless, of course, your goal is only to be compatible with SDR.

**Comment by mathias-ewald** [comment]
Thanks for pointing that out. I'll have a look!
