### ISSUE TITLE
Argument of type 'string' is not assignable to parameter of type 'new () => Resource'

### ISSUE THREAD

**Issue by mathias-ewald** [lagoshny/ngx-hateoas-client#12]
I followed the instructions of the readme but get the following error for the code to create a new resource:

<img width="1321" alt="Screenshot 2021-09-28 at 21 44 09" src="https://user-images.githubusercontent.com/35083480/135155333-0b31163c-7991-4bce-96a6-3e869b9abc1a.png">

**Comment by lagoshny** [comment]
Hi @mathias-ewald, which version of lib do you use? 1.x or 2.x?

**Comment by lagoshny** [comment]
@mathias-ewald, I have published 2.0.0 release and READE.ME documentation updated, try this version.

**Comment by mathias-ewald** [comment]
Running `npm i @lagoshny/ngx-hateoas-client --save` gave me `"@lagoshny/ngx-hateoas-client": "^2.0.3-beta"` in the `package.json`. I got it to work with

```
this.resourceService.createResource<Project>(Project, { body: project })
```

So considering the version and that fact that it works, I am wondering if this is just to be updated in the documentation.

**Comment by lagoshny** [comment]
Yes, documentation is already updated (before documentation was for 1.x.x versions), now it is actually for 2.x.x versions and you can use it.

**Comment by mathias-ewald** [comment]
Great, thanks!
