### ISSUE TITLE
Configuration of halFormat.embeddedOptional requires specification of halFormat.json

### ISSUE THREAD

**Issue by K-e-l-v-i-n-12** [lagoshny/ngx-hateoas-client#120]
First of all, many thanks for the quick implementation of change requests. As part of issues-116, there was a change in the configuration which should be discussed again if necessary.

Previously, we overwrote the halFormat.collections.embeddedOptional setting in our project with the value we wanted. Since the extension of halFormat by json.convertEmptyObjectToNull, an error occurs here. The default config values are not adopted for json.convertEmptyObjectToNull. Instead, both values must now be defined so that the application can run. It might make sense to change this behavior.

**Comment by lagoshny** [comment]
Thank you for the issue. Fixed in 3.8.1 version
