### ISSUE TITLE
Impossible to send custom POST request

### ISSUE THREAD

**Issue by sergey-morenets** [lagoshny/ngx-hateoas-client#124]
Hi 

We have Order entity and corresponding OrderService:

```
@Injectable()
export class OrderService extends HateoasResourceOperation<Order> {
```

We can't use createResource method because it requires Order as a body (while we use other DTO class).
But can't use customQuery method either:

`    return this.customQuery(HttpMethod.POST, '', {body: createOrderCmd});`

Because of the error where this library complains about empty **query** parameter:

`Error: Passed param(s) 'query'`

So we have to use this ugly solution as workaround:

`return this.createResource({body: createOrderCmd as any});`

Are there any more suitable solution?

**Comment by sergey-morenets** [comment]
> Hi
> 
> I think it is not good to require `query` param in `customQuery` for `POST` requests. I will change it behaviour.
> 
> What about question. If you want to get some another DTO class that is NOT resource. You can inject `HttpClient` directly to the `OrderService` and perform any requests.

Thank you.

**Comment by lagoshny** [comment]
Closed the issue due not activity.
