### ISSUE TITLE
Failed to determine resource route by url

### ISSUE THREAD

**Issue by gguptha** [lagoshny/ngx-hateoas-client#126]
> Error: Failed to determine resource route by url: http://localhost:8080/api/users/57098dbd-2d62-4812-afca-2b2764ecebb3
>     at UrlUtils.guessResourceRoute (lagoshny-ngx-hateoas-client.mjs:600:19)
>     at UrlUtils.getResourceNameFromUrl (lagoshny-ngx-hateoas-client.mjs:628:40)
>     at ResourceUtils.findResourceName (lagoshny-ngx-hateoas-client.mjs:991:25)
>     at ResourceUtils.createResource (lagoshny-ngx-hateoas-client.mjs:820:35)
>     at ResourceUtils.instantiateResource (lagoshny-ngx-hateoas-client.mjs:758:21)
>     at lagoshny-ngx-hateoas-client.mjs:880:48
>     at Array.forEach (<anonymous>)
>     at ResourceUtils.instantiateResourceCollection (lagoshny-ngx-hateoas-client.mjs:879:52)
>     at lagoshny-ngx-hateoas-client.mjs:1634:34
>     at map.js:7:37
> 

I get the above error when the below code is executed -

`return this._hateoasResourceService.getCollection(UserResource);
`

This should return a collection of users, instead I get the above error.

**Comment by gguptha** [comment]
Version used : 3.8.1

```
    constructor(config: NgxHateoasClientConfigurationService) {
        config.configure({
            http: {
                rootUrl: environment.hateoasApiHost
            },
            useTypes: {
                resources: [
                    InstanceResource,
                    UserResource
                ]
            },
            cache: {
                enabled: false
            }
        })
    }

```

**Comment by lagoshny** [comment]
Provide value of `environment.hateoasApiHost`

**Comment by gguptha** [comment]
hateoasApiHost: 'https://pfa1.cloudledger.io/api',

I also added  isProduction: true to the config.

My spring boot server is running on a AWS EC2 instance, behind nginx, I noticed this error after I deployed my app for production (with angular production build). When I run my app on my local system in development mode, all seems to work fine.

**Comment by lagoshny** [comment]
In your backend API, what URL specifies in `_links` object? Does it match to `https://pfa1.cloudledger.io/api`?

The errors occur because `rootUrl = https://pfa1.cloudledger.io/api` does not match to the resource URL `http://localhost:8080/api`.
If you use nginx, try to set up `proxyUrl` in configuration that match to `Resource` URL.

**Comment by lagoshny** [comment]
Any news?

**Comment by gguptha** [comment]
The URL in the _links were coming up as localhost:8080. I fixed that and it solved the problem. 
Thanks for pointing out the issue.
