### ISSUE TITLE
Not reload subdata

### ISSUE THREAD

**Issue by airjord** [lagoshny/ngx-hateoas-client#14]
Hi, i am using your ngx-hateoas-client in a angular project to connect to a sping data rest backend. 

**Describe the issue**

the subrelation (onToMany) will not be resolved by the client ngx-hateoas-client. 

I follow the full example described in the documentation.
I am using the built-in service, We have a object with hold a other object (Order contains OrderPos).
 
We have the issue that the embedded object get not loaded. 

```
@HateoasResource('order')
export class Order extends Resource {
   public orderNo: string;
   public orderPos: OrderPos;
}

@HateoasResource('orderPos')
export class OrderPos extends Resource {
   public quantity: string;
}


export class DeliveryDetailComponent implements OnInit, OnDestroy {
.....
order = new Order();
this.resourceHateoasService.getPage(Order)
    .subscribe((page: PagedResourceCollection<Order>) => {
        const orders: Array<Order> = page.resources;  
        console.log(orders);  // --> Object orderPos in order not available and is not loaded from the backend. 
    });
```
**Expectation**

The expectation is that the client loads all relations if defined in the classes of the object (Order --> OrderPos). All is working fine but the "SubObject --> OrderPos" is not loaded.

**Comment by lagoshny** [comment]
Hi @airjord,

Thank you for a detailed description of the problem.

By default, Spring Data Rest doesn't fill relations as objects in the response, it only passes links to relations in _link array property.
This is the reason why object relations are empty. 

**ngx-hateoas-client** provides only a convenient form to work with Spring Data Rest server-side, it does not add extra logic by making additional requests to fetch all relations. It uses responses from the server-side and wraps them in Resource classes that help to work with them.

To do what you want, you can use **projections** for the Order resource.
You can read more about Projection on the server-side [here](https://www.baeldung.com/spring-data-rest-projections-excerpts).

After when you create a projection on the server-side, you can create it on the client-side as follows:

1. Create a new model class mapped to the server-side projection:
```
@HateoasProjection(Order, 'orderProjection')
export class OrderProjection extends Resource {

  public orderNo: string;

  @ProjectionRel(OrderPos)
  public orderPos: ProjectionRelType<OrderPos>;

}
```
2. Use the projection resource type when you want to get projection data. 
For your example:
```
this.resourceHateoasService.getPage(OrderProjection)
    .subscribe((page: PagedResourceCollection<OrderProjection>) => {
        const orders: Array<OrderProjection> = page.resources;  
        console.log(orders);  // --> Object orderPos will not be empty if you pass it in the server-side projection
    });
```

**Comment by thhart** [comment]
Thanks for clarification again, maybe it is worth to put this into a readable docu anywhere?

**Comment by lagoshny** [comment]
Yes, will put it in the lib documentation.
