### ISSUE TITLE
Different URLs for different Resources

### ISSUE THREAD

**Issue by mathias-ewald** [lagoshny/ngx-hateoas-client#19]
I have two services to access different entities / resources of my REST API. The two resources are hosted on different API endpoints, so I was wondering how to configure separate `rootUrl` per resource. I couldn't figure it out from the extensive documentation you have there. Maybe I overlooked it, though.

**Comment by lagoshny** [comment]
Hi @mathias-ewald,

You are right. Currently, the lib has not support several URLs to get resources.

I think, you can use some proxy server to get this (like nginx) that will provide one point to get several entities from several URLs.

If nginx has not helped you, write about it, I will think what can to do with this.

**Comment by mathias-ewald** [comment]
Hi @lagoshny, thanks for the swift reply. Good to hear that I didn't just not find it :D So, yeah, I was thinking of a reverse proxy as a possible solution, too, but had the hopes to being able to avoid it. Anyway, I was able to set up what I need with Spring Cloud Gateway fairly quickly. On Kubernetes, I might resort to an Ingress. We'll see :)

```
@SpringBootApplication
public class Application {

	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
	}

	@Bean
	public RouteLocator gateway(RouteLocatorBuilder rlb) {
		return rlb.routes()
			.route(routeSpec -> routeSpec
				.path("/projects/**")
				.filters(gatewayFilterSpec -> gatewayFilterSpec.setPath("/projects"))
				.uri("http://localhost:8081/")
			)	
			.route(routeSpec -> routeSpec
					.path("/exports/**")
					.filters(gatewayFilterSpec -> gatewayFilterSpec.setPath("/exports"))
					.uri("http://localhost:8082/")
			)	
			.build();
	}
}
```
