### ISSUE TITLE
GetOption and RequestOption do not provide options to modify HttpRequest

### ISSUE THREAD

**Issue by dhoeppe** [lagoshny/ngx-hateoas-client#21]
I'm currently in a situation where I have a client that can perform actions on behalf of itself and on behalf of users.

Clients are authenticated through OAuth while users are authenticated through a custom solution.
OAuth uses the `Authorization` header and the custom solution uses cookies.

The client therefore needs the option to present itself as client or as user.
ngx-hateoas-client currently has no option to modify the `HttpRequest` that it sends to the server or pass any intention on to a `HttpInterceptor` to indicate how to modify the request.

To fix this I would introduce a way into `GetOption` and `RequestOption` to modify the request, for example like in `HttpInterceptor`.

As you are more familiar with your library, do you see any other way to achieve this?

**Comment by lagoshny** [comment]
Hi @dhoeppe ,

If I understand your problem, you want to add an interceptor to handle additional logic while resource request.
`ngx-hateoas-client` uses your project's `HttpClient` and you can add an `HttpInterceptor` to it, and it will handle resource requests too. 
You can see an example how add BasicAuth to the project that uses `ngx-hateoas-client` [here](https://github.com/lagoshny/task-manager-front/blob/master/src/app/core/interceptors/basic-auth.interceptor.ts).

If it is not your case and your issue is another, can you provide some examples to describe the issue additionally.

**Comment by dhoeppe** [comment]
I have two identities:
- Client (FIND Person)
- User (CREATE Person)

The application can use both identities to handle resources.

Client: 
`personService.createResource(newPerson)` -> `401 Unauthorized`
`personService.getResource(1)` -> `200 OK`

User (id: 1):
`personService.createResource(newPerson)` -> `201 Created`
`personService.getResource(1)` -> `200 OK`
`personService.getResource(3)` -> `401 Unauthorized`

I need a way to indicate `ngx-hateoas-client` to perform requests on behalf of one of the identities, i.e.:

`personService.createResource(newPerson, { authentication: user })`
`personService.getResource(3, { authentication: client })`

A `HttpInterceptor` cannot know which identity to use, as the target URL can be the same and there is no further indication on the request.

This can for example be fixed by:

`
personService.createResource(newPerson, {
  headers: {
    'Authorization': 'Bearer ...'
  }
})
`
or
`
personService.createResource(newPerson, {
  withCredentials: true
}
`

I was wondering if you agree with this or if you have another solution.

Best Regards,
Daniel

**Comment by dhoeppe** [comment]
I thought about it, and it would be possible using the `HttpInterceptor` and a second service. For example:

`
authenticationService.setActiveIdentity(user);
personService.createResource(newPerson)...
authenticationSerivce.usetIdentity() // if required;
`

and a `HttpInterceptor` with

```
intercept() {
  if(authenticationService.getActiveIdentity() == user) {
    return request.clone({withCredentials: true});
  } else {
    return request.clone({headers: {'Authorization': 'Bearer ...'}});
  }
}
```

So I'm not sure if the library needs change. Which way do you prefer?

Best Regards,
Daniel

**Comment by lagoshny** [comment]
@dhoeppe thank you for the detailed description. 
I will think how to do this. Most likely, I will add the possibility to put an HTTP header to a resource request.

I need some time for this, when I have done this I let to know you.

**Comment by lagoshny** [comment]
@dhoeppe, I added to `RequestOption` additional params that can used by Angular `HttpClient`. Now you can pass HttpHeaders use this.

New version **2.2.1** already published to the npm.

All changes you can see [here](https://github.com/lagoshny/ngx-hateoas-client/blob/master/CHANGELOG.md#221-2021-12-05).
