### ISSUE TITLE
Case sensitive url manipulation

### ISSUE THREAD

**Issue by gabmilg** [lagoshny/ngx-hateoas-client#26]
Great project! 👍 
I would suggest to make case insensitive `api url` replacement.
Took me a while to understand why I'm getting error `Not found resource type when create resource...`
https://github.com/lagoshny/ngx-hateoas-client/blob/411817d7e7cab97438dc99fcdf272b5c4f4d6f00/projects/ngx-hateoas-client/src/lib/util/url.utils.ts#L127

**Comment by lagoshny** [comment]
Hi @gabmilg ,
Thanks for the issue.

I fixed it in the new lib version, try it from NPM.
