### ISSUE TITLE
Relativ rootUrl possible?

### ISSUE THREAD

**Issue by thomaspz** [lagoshny/ngx-hateoas-client#34]
My Application runs on a subpath

`     www.example.de/myapplication/index.html`

and rootUrl ist configured as

`    rootUrl: './api/'`

But all RestCalls result in

`    www.example.de/api/xxxx`
    
instead of expected

`     www.example.de/myapplication/api/xxxx`
     
Is there a way to configure ngx-hateoas-client for a relativ rest url?

**Comment by lagoshny** [comment]
Try to change `rootUrl` to `'./myapplication/api/'`.

Possibly I didn't understand your question.
If it is not help you, add additional info about backend and frontend environments. Is it using nginx as proxy or not?

**Comment by thomaspz** [comment]
Yes that worked

rootUrl '/myapplication/api/'

I thought if I define a relative URL it  would be appended to the window.location.href and not to the window.location.host; But I recognized that with angular-routing there are pseudo urls like 

/myapplication/dashboard or /myapplication/user

So I think, that couldn't work, because the client lib couldn't extract the "real" base-path of the application, or?

I will use the "fixed definied rootUrl and I repackage the application if the url changes. I though I could avoid repackaging with relativ rootURL If the "base-url" changes.

Thanks for your help.

**Comment by lagoshny** [comment]
Closed the issue due inactivity.
