### ISSUE TITLE
Templated self links not working

### ISSUE THREAD

**Issue by Tqup3** [lagoshny/ngx-hateoas-client#37]
Hello guys,

I have an issue with a self href link that is templated.
It looks like : "self: {href: "http://localhost:8081/chronos/api/tasks/-11{?projection}", templated: true}"

My server (spring-data-rest) model is a tree :

```
@Projection(name = "default", types = {Task.class})
public interface TaskExcerpt {
    long getId();
    String getName();
    Collection<TaskExcerpt> getTasks();
}
```

In typescript :
```
@HateoasResource('tasks')
export class Task extends Resource {
    name!: string;

    @ProjectionRel(Task)
    tasks!: Task[];
}

@HateoasProjection(Task, 'default')
export class TaskExcerpt extends Resource {
    name!: string;

    @ProjectionRel(Task)
    tasks!: ProjectionRelType<Task>[]; // Can't set type to ProjectionRelType<TaskExcerpt>[];
}
```

Issue is when I try to deleteRelation between a Task and another `parent.deleteRelation('tasks', task).subscribe();`.
The HTTP request is wrong and looks like : `DELETE http://localhost:8081/chronos/api/tasks/-2/tasks/-21%7B?projection}`
instead of something like : `DELETE http://localhost:8081/chronos/api/tasks/-2/tasks/-21`

I think the issue is in the resource.ts file in getSelfHrefLink() method. This method doesn't take care about templated self uri.
I tried to override this method with my own implementation of the getSelfHrefLink() method in a inherited class but it doesn't work.

I tried with/without @ProjectionRel annotation, ProjectionRelType type, Task/TaskExcerpt type. Url is always wrong.

Thanks for your help :)

**Comment by lagoshny** [comment]
@Tqup3, 
Hi, thank you for the issue.

I fix it in the new release, that already published to the NPM, you can try it.

**Comment by Tqup3** [comment]
Hi @lagoshny,

Thanks for your fast fix/reply. I'll test that on next sunday and i'll keep you in touch.

**Comment by Tqup3** [comment]
Hi @lagoshny,

Sorry for late answer, I've just tested your fix and it works like a charm.
I close the topic.

Thanks for your help :)
