### ISSUE TITLE
Error in customPage().

### ISSUE THREAD

**Issue by Knusperkroete** [lagoshny/ngx-hateoas-client#40]
Hello,

unfortunately i had some problems with the customPage-method, but it might be me who is using it wrong.

The first one is contained in line 164 and 165. I think the maxPageNumber should rather be "Math.floor(this.totalElements / this.pageSize)", than "(this.totalElements / this.pageSize) - 1". Otherwise the if-condition in line 165 is true, when the elements don't add up to a full page on the last page or maxpage numer could be between -1 and 0 if the totalElements are not enough for a whole page.

The second issue i ran into, has to do with the lines 170  and 171. The if-condition in line 171 will for all pages, except the first one, be true, so the error will always be activated.

I am looking forward for your answer.

**Comment by lagoshny** [comment]
@Knusperkroete , thanks for the feedback. 
Fixed it too in new versions for **old Angular 2.3.8** and for the **last Angular 3.0.8**.
