### ISSUE TITLE
Bug When API Is At Context Path

### ISSUE THREAD

**Issue by mathias-ewald** [lagoshny/ngx-hateoas-client#48]
I moved my API endpoint from `http://localhost:8080` to `http://localhost:8080/api` and since you're documenting that at https://github.com/lagoshny/ngx-hateoas-client/blob/master/README.md?plain=1#L165 I didn't give it much thought until I noticed some calls aren't working anymore.

On one page, I am fetching all `Project`s and it works just fine since the call goes to `http://localhost:8080/api/projects` as expected.
```
this.projectService.getCollection().subscribe(all => {
    this.projects = all.resources;
});
```

Then on a different page, that allows me to modify a `Project`, when I run
```
this.projectService.updateResource(this.project).subscribe();
```
the call goes to `http://localhost:8080/apiprojects/62499fea3c9abf4e937c4df0`. Obviously, there's a `/` missing.

Here some more code to see how I configure and use the library:

**project.service.ts**
```
@Injectable({ providedIn: 'root'})
export class ProjectService extends HateoasResourceOperation<Project> {
  constructor() {
    super(Project);
  }
}
```

**project.ts**
```
@HateoasResource('projects')
export class Project extends Resource {
    ...
    constructor()
    constructor(name: string, atem: Atem)
    constructor(name?: string, atem?: Atem) {
        super();
        ...
    }

    get public(): boolean {
        return this.owner == null;
    }
}
```

**app.module.ts**
```
@NgModule({
  declarations: [
    AppComponent,
    ...
  ],
  imports: [
    ...
    NgxHateoasClientModule.forRoot()
    ...
  ],
  providers: [
    ProjectService,
    ...
  ],
  bootstrap: [AppComponent]
})
export class AppModule {

  constructor(hateoasConfig: NgxHateoasClientConfigurationService) {
    hateoasConfig.configure({
      http: {
        rootUrl: environment.apiUrl,
      },
      useTypes: {
        resources: [Project]
      }
    });
  }
  
}
```

**environment.ts**
```
import * as config from './config.json';
export const environment = config;
```

**config.json**
```
{
  "apiUrl": "http://localhost:8080/api",
  ...
}
```

I tried using `http://localhost:8080/api/` for the `apiUrl` but no success.

**Comment by lagoshny** [comment]
Hi @mathias-ewald , 

Did you solve the problem?

**Comment by mathias-ewald** [comment]
Yeah, approx 2.1s after I created the issue, I realized what was the problem and that it was my own fault xD
