### ISSUE TITLE
Libraries should not import HttpClientModule

### ISSUE THREAD

**Issue by mbursill** [lagoshny/ngx-hateoas-client#49]
The HttpClientModule should only be imported in the app module (the bootstrapped module) and not library modules. This is noted in this lengthy discussion: https://github.com/angular/angular/issues/20575

By importing HttpClientModule in ngx-hateoas-client.module.ts the module is essentially reset for the library and any custom interceptors used by the app will be ignored.

**Comment by lagoshny** [comment]
Hi @mbursill ,
Thanks for the provided information. I saw the Angular Issue and remove HttpClientModule from importing ngx-hateoas-client. This changes available in `3.1.0` for Angular 12+ versions or `2.4.0` for old Angular versions.
