### ISSUE TITLE
using searchPage but got 404 not found

### ISSUE THREAD

**Issue by Choupa-web** [lagoshny/ngx-hateoas-client#52]
Hello,

Thank you for your lib, it's really great !

I'm using getPage without any problem, the url generated is **http://localhost:4200/refclearing/api/codes?page=0&size=25**

but when I want to use searchPage, I have a 404 not found error. Url generated is : **http://localhost:4200/refclearing/api/codes/search/searchQuery?codeCampaign=CCYOP2201&page=1&size=25&sort=cost,ASC**

my code: 
`this.codeService.searchPage('searchQuery', {  
pageParams: { page: 1,  size: 25
      },
      params: {
        codeCampaign: 'CCYOP2201'
      },
      sort: {
        cost: 'ASC'
      }})`

I'm wondering what I did wrong...

**Comment by lagoshny** [comment]
Hi! `search` methods means that you have in server-side custom Spring Data Repository method.

For your example, you need to have a method like this:

```java
@RepositoryRestResource(path = "codes")
public interface CodeRepository extends JpaRepository<Code, Long> {

    @RestResource(path = "searchQuery", rel = "searchQuery")
    Page<Code> searchQuery(@Param("codeCampaign") String codeCampaign, Pageable pageable);

}
```

Each custom methods in Spring Data Repository spring public them under `/search/` path and use `@RestResource` annotation to define method path.

In summary, `searchPage` method builds the URL:
The first part is the path to the resource: `http://localhost:4200/refclearing/api/codes`
Next adds default spring path for the custom Data Repo methods: `/search/`
And name search query passed in first parameter in your example is: `searchQuery`
Finally, adds passed request parameters like `codeCampaign`, `sort`, `page`.

**Comment by Choupa-web** [comment]
Got it ! Thanks a lot
