### ISSUE TITLE
Using Date field in Resource class produce a String value instead of Date

### ISSUE THREAD

**Issue by StPessina** [lagoshny/ngx-hateoas-client#55]
Dear hateoas client's team,

First at all, thanks you for this great work!

I'm trying to use Date field in a resource class:
`@HateoasResource('delivery_rounds')
export class DeliveryRound extends Resource {
  scheduledAt: Date;
}`

Using a Spring repository @RepositoryRestResource, from the API I get the value formatted as:
`{
  "_embedded": {
    "delivery_rounds": [
      {
        "scheduledAt": "2022-06-20T04:00:00",
        "_links": 
....other hateoas stuff.....
`  

However, if I print the type of the scheduledAt field it's a string type instead a Date. 

How I can get a Date type in the resource after collect it?

Thanks you.
Stefano

**Comment by lagoshny** [comment]
My first fix has a bug, now I redid it.
If you need to parse properties as `Date` you need to specify in lib configuration `Date` format parameters.
You can read more in [documentation](https://github.com/lagoshny/ngx-hateoas-client#typesformat).

If no date formats defined or property does not match date format, then date will parse as before as raw string.

This changes available in lib version: `2.4.2` for old Angular and `3.1.2` for new Angular.

**Comment by StPessina** [comment]
Hi @lagoshny 

Thanks you so much for the fix!
