### ISSUE TITLE
Error: Failed to determine resource route by url

### ISSUE THREAD

**Issue by Choupa-web** [lagoshny/ngx-hateoas-client#61]
Hi,

We upgraded @lagoshny/ngx-hateoas-client from 3.1.2 to 3.2.0. Now when we access to a page which uses hateoas methods we have the following message : 

**Error: Failed to determine resource route by url: http://evercampaign.local.budget-box.com/api/codes/62baa35433dd613e2828417c**

if I open the above url with a small update it works : 
http://evercampaign.local.budget-box.com/refclearing/api/codes/62baa35433dd613e2828417c

Related to update 3.2.0 I updated following files:

**app.module.ts**

> hateoasConfig.configure({
       http: {
         defaultRoute: {      
                 rootUrl:  `${environment.baseUrl}`
         }
       },
       useTypes: {
         resources: [Code]
      }
    });

**code.model.ts**

> @HateoasResource('codes', { routeName: 'defaultRoute' })
export class Code extends Resource {
  public id?: number;

We use a proxy: 

> "/refclearing/api/*": {
    "target": "http://evercampaign.local.budget-box.com",
    "secure": false,
    "changeOrigin": true
  }

**Comment by lagoshny** [comment]
Hi @Choupa-web ,

Can you add info about your previous `http` lib configuration. 
Did you set `proxyUrl` in previous `http` config?

**Comment by Choupa-web** [comment]
previous configuration of http lib was : 

>  hateoasConfig.configure({
      http: {
        rootUrl: `${environment.baseUrl}`
      },
      useTypes: {
        resources: [Code] } });

the proxyUrl was already setup before.

**Comment by Choupa-web** [comment]
yes If I use old http config I have the same error
I use getPage() and createResource() which throw the exception

**Comment by lagoshny** [comment]
@Choupa-web 
Fixed this bug in new Angular versions: `3.2.1` for new one and `2.5.1` for old.

Don't forget to configure your `proxyUrl` in lib config.

P.S. You don't need to set up `routerName` as `defaultRoute` on `@HateoasResource` decorator, it defaults value for this parameter.

**Comment by lagoshny** [comment]
@Choupa-web 
Fixed this bug in new lib versions: `3.2.2` for new Angular and `2.5.2` for old Angular .

Don't forget to configure your `proxyUrl` in lib config.

P.S. You don't need to set up `routerName` as `defaultRoute` on `@HateoasResource` decorator, it defaults value for this parameter.

**Comment by Choupa-web** [comment]
Hello,
I updated to version 3.2.2 and I also added the proxyUrl information:

>  hateoasConfig.configure({
      http: {
        proxyUrl: 'http://evercampaign.local.budget-box.com',
        rootUrl:  `${environment.baseUrl}`
      },
      useTypes: {
        resources: [Code]
      }
    });


I don't have the error message "Failed to determine resource..." anymore. Instead I have : 

**Access to XMLHttpRequest at 'http://evercampaign.local.budget-box.com/codes?page=0&size=25' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.**

**Comment by lagoshny** [comment]
Hi,
You need to configure `server` to accept `CORS` requests from your frontend app, see more about CORS [here](
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).
It happens because your `front` and `back` apps hosted by different hosts.

**Comment by lagoshny** [comment]
@Choupa-web, have you solved the problem?
