### ISSUE TITLE
Is it possible to clear the cache ?

### ISSUE THREAD

**Issue by Tqup3** [lagoshny/ngx-hateoas-client#70]
Hello @lagoshny,

Is it possible to clear all data stored in the cache ?

Because when switching user in my web app (a user with less role than the first one), the cache of the previous user is still used for the new one. So the new user can see more information that it should see.

If it doesn't exist, is it possible to add a function like : cacheService.clear() ? Which I can call when a user is disconnecting.

Best regards,
Tqup3

**Comment by lagoshny** [comment]
Hi @Tqup3 ,
Added  `HateoasResourceService#evictResourcesCache` method that allows to evict all resources cache.
See more in [docs](https://github.com/lagoshny/ngx-hateoas-client#evict-all-cache-data).

This method available in `3.3.2` lib version for new Angular and `2.6.2` for old.

**Comment by Tqup3** [comment]
Many Thanks,

Fastly and efficiently as usual ;)
I didn't test yet but it should be ok on my side
