### ISSUE TITLE
TypeError (resourceOptions is undefined) after upgrade to newest ngx-hateoas-client version

### ISSUE THREAD

**Issue by K-e-l-v-i-n-12** [lagoshny/ngx-hateoas-client#72]
We would like to upgrade our angular project to the latest ngx-hateoas-client version. Unfortunately, we get a TypeError when doing this. In older versions the code ran without problems. 

Error:
> ERROR TypeError: resourceOptions is undefined
    generateLinkUrl lagoshny-ngx-hateoas-client.mjs:507
    getRelation lagoshny-ngx-hateoas-client.mjs:1689
    getGarage car-overview.component.ts:44

Code:
> this.resourceHateoasService.getCollection(Car, { params: { color: "red"} })
  .pipe(map(page => page.resources))
  .pipe(flatMap(x => x))
  .subscribe(car => {
    car.getRelation<Garage>("garage").subscribe(garage => console.log(garage.name));
  });

**Comment by lagoshny** [comment]
Can you provide info about `car` model class? Is it annotated with `@HateoasResource('resourceName')`?
​Do you have some warnings messages in console?

And can you provide log info about constructor car object in subscribe point:

```ts
.subscribe(car => {
     console.log(car);
     ...
});
```

And provide info about prototype, something like this:

```ts
<prototype>: Object { … }
	constructor: class yf {}​​​
		__options__: Object { routeName: "defaultRoute" }
		__resourceName__: "task-categories"
                ....
```

**Comment by lagoshny** [comment]
@K-e-l-v-i-n-12 I found potential problem.

Try last version `3.3.3` for new Angular and `2.6.3` for old.

**Comment by K-e-l-v-i-n-12** [comment]
@lagoshny The new version (3.3.3) works great - the issue is fixed.

In addition, I found out that the car resource does not contain a self link (also logged on the console). This only caused problems in version 3.3.2. The self link may be missing in the new version. Of course I've added it now.

Thank you again for the quick adjustment.
