### ISSUE TITLE
Receiving wrong Type after getRelation

### ISSUE THREAD

**Issue by mathias-ewald** [lagoshny/ngx-hateoas-client#74]
Hi, tbh, I am not sure where this comes from but posting it here seems like a reasonable first step:

```
this.resourceService.createResource(Query, request).pipe(
  filter((query: Query) => query.hasRelation('result')),
  tap(o => console.log(o)),
  mergeMap((query: Query) => query.getRelation<Result>('result').pipe(retry(retryCfg))),
  tap(o => console.log(o))
).subscribe();
```

As you can see, I am 
1. creating a `Query`
2. resolving the `result` relation of type `Result` with a `retry` (tried without retry but same problem)
3. put some `console.log` in between to see what's being returned

The console output looks like this:
![Screenshot 2022-08-01 at 09 45 01](https://user-images.githubusercontent.com/35083480/182098975-e4a8141d-80c4-474b-9b96-4ab0aae6564e.png)

The 2nd line should be a `Result` object, not `Query` with the fields from `Result`. Any ideas why it happens like this?

```
@HateoasResource('queries')
export class Query extends Resource {
    constructor()
    constructor(queryString: string)
    constructor(public queryString?: string) {
        super();
    }
}

@HateoasResource('results')
export class Result extends Resource {
    public articles?: Article[];
}
```

**Comment by mathias-ewald** [comment]
I just ran a little test:

```
export class Foo {
  constructor(public foo: string) {}
}
export class Bar {
  constructor(public bar: string) {}
}

from([new Foo("FOO")]).pipe(
  tap(o => console.log(o)),
  mergeMap(o => from([new Bar("BAR")]))
).subscribe(r => console.log(r));
```

The output is a `Bar` object, not a `Foo` with a `bar` field. Makes me think it comes from the library.

**Comment by lagoshny** [comment]
Hi @mathias-ewald ,

This can be if the result of `query.getRelation<Result>('result')`  returns `JSON` with self link in `_links` object as link to `query` resource. Can you provide `JSON _links` object that returned from  `query.getRelation<Result>('result')` call?

**Comment by lagoshny** [comment]
For example, you have some `Task` resource:

````ts
@HateoasResource('tasks')
export class Task extends Resource {
...
}
````

and `JSON` of this resource something like this:

````json
{
  "id" : 12,
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/api/v1/tasks/12"
    },
    "task" : {
      "href" : "http://localhost:8080/api/v1/tasks/12{?projection}",
      "templated" : true
    },
    "category" : {
      "href" : "http://localhost:8080/api/v1/tasks/12/category"
    }
  }
}
````

Lib considers that this `JSON` as `Task` resource object because in self link 
````json
    "self" : {
      "href" : "http://localhost:8080/api/v1/tasks/12"
    }
````
/api/v1/**tasks**/12 matches to name of @HateoasResource(**'tasks'**)

And then it created `Task` resource object.

And if you api call `query.getRelation<Result>('result')` returned `JSON` where `self.href` link has a `queries` in the path, then it can create `Query` resource.

Therefore, I need info about `_links` object in `JSON` after `query.getRelation<Result>('result')` call.

**Comment by mathias-ewald** [comment]
Yes, you're right. The returned href for the `result` relation is `/queries/ID/result` rather than `/results/ID`. I guess that I can argue to be changed in the backend. 

Nonetheless, checking https://datatracker.ietf.org/doc/html/draft-kelly-json-hal again, I cannot find anything that enforces the behavior the library expects.

**Comment by lagoshny** [comment]
I think this point wrote in [this](https://datatracker.ietf.org/doc/html/draft-kelly-json-hal#section-8.1) section.

Link like `/queries/ID/result` usually used as link to relation `result` in `query._links` object.

But when you get `result` resource using `/queries/ID/result` link, then `JSON` should contain `_links.self.href=/results/ID` it means that this JSON about resource that you can get using `self` link.
