### ISSUE TITLE
embedded resources are empty - invalid JSON or a bug?

### ISSUE THREAD

**Issue by K-e-l-v-i-n-12** [lagoshny/ngx-hateoas-client#76]
I would like to expand our previous project in such a way that embedded resources will also be sent in the future. I therefore first adapted our backend accordingly, which returns the following json object:
````
{
   "id":"d589852f-0b3f-4025-86cb-2fa3b35a1339",
   "color":"red",
   "brand":"Volkswagen",
   "model":"Golf",
   "garageId":"096a07ea-3970-4968-9cd9-4756ae6a9cb1",
   "_links":{
      "self":{
         "href":"https://localhost:8443/api/v1/cars/d589852f-0b3f-4025-86cb-2fa3b35a1339"
      },
      "inspections":{
         "href":"https://localhost:8443/api/v1/cars/d589852f-0b3f-4025-86cb-2fa3b35a1339/inspections"
      },
      "garage":{
         "href":"https://localhost:8443/api/v1/garages/096a07ea-3970-4968-9cd9-4756ae6a9cb1"
      }
   },
   "_embedded":{
      "inspections":[
         {
            "id":"405624d4-b3de-461a-a256-38ca3c291450",
            "name":"XY",
            "date":"DD.MM.YYYY",
            "carId":"d589852f-0b3f-4025-86cb-2fa3b35a1339",
            "_links":{
               "self":{
                  "href":"https://localhost:8443/api/v1/inspections/405624d4-b3de-461a-a256-38ca3c291450"
               },
               "car":{
                  "href":"https://localhost:8443/api/v1/cars/d589852f-0b3f-4025-86cb-2fa3b35a1339"
               }
            }
         }
      ],
      "garage":{
         "id":"096a07ea-3970-4968-9cd9-4756ae6a9cb1",
         "location":"XY",
         "surface":"pavement",
         "city":"XY",
         "_links":{
            "self":{
               "href":"https://localhost:8443/api/v1/garages/096a07ea-3970-4968-9cd9-4756ae6a9cb1"
            },
            "cars":{
               "href":"https://localhost:8443/api/v1/garages/096a07ea-3970-4968-9cd9-4756ae6a9cb1/cars"
            },
            "inspections":{
               "href":"https://localhost:8443/api/v1/garages/096a07ea-3970-4968-9cd9-4756ae6a9cb1/inspections"
            }
         }
      }
   }
}
````

Then I created the two embedded classes GarageItemEmb and InspectionItemEmb and extended my CarItem accordingly. (In the future it would be nice if I could use a class both as a Resource and as an EmbeddedResource.):

````
@HateoasEmbeddedResource(['garage'])
export class GarageItemEmb extends EmbeddedResource {
  public id: string;
  public location: string;
  public surface: string;
  public city: string;
  public city: string;
}

@HateoasEmbeddedResource(['inspections'])
export class InspectionItemEmb extends EmbeddedResource {
  public id: string;
  public name: string;
  public date: string;
}

@HateoasResource('cars')
export class CarItem extends Resource {
  public id: string;
  public color: string;
  public brand: string;
  public model: string;
  public garageId: string;
  public garage: GarageItemEmb;
  public inspections: InspectionItemEmb[];
}
````

Then the classes are registered:
````
      useTypes: {
          resources: [ CarItem ],
          embeddedResources: [ GarageItemEmb, InspectionItemEmb]
      },
````

However, if I now get an item of the CarItem type, then both garage and inspections are undefined?

Did I make a mistake or is there a bug here?

**Comment by lagoshny** [comment]
Hi @K-e-l-v-i-n-12 ,

I think in your case `inspections` and `garage` it is not EmbeddedResource's.
I meant by concept [EmbeddedResource](https://github.com/lagoshny/ngx-hateoas-client#embeddedresource) that it like `Embeddable` components in the `JPA`.
Such `Embeddable` components haven't an id property key and cannot exist without "parent" entity that contains it.

In your case both  `inspections` and `garage` have `self` links, therefore they have an id property, and you can use in this case simple `Resource` type.

**Comment by K-e-l-v-i-n-12** [comment]
Hello @lagoshny,
Sorry for my late answer. There have been numerous sideshows lately.

I understand your statements that you assume Embeddable in the JPA context for EmbeddedResource. In my explanationI assumed the embedded support of Spring hateoas. For me, this is an essential feature of spring hateoas, which also greatly minimizes additional requests.

Unfortunately, as far as I know, there is currently no way in the ngx-hateoas-client to access embedded resources.

More information and examples can be found here: [spring-hateoas - issue 270](https://github.com/spring-projects/spring-hateoas/issues/270)

I would be very happy about a corresponding implementation.
