### ISSUE TITLE
feature request: add useCache-default property

### ISSUE THREAD

**Issue by K-e-l-v-i-n-12** [lagoshny/ngx-hateoas-client#77]
In the previous versions of ngx-hateoas-client, the cache is activated (true) by default. For individual calls, the cache can be (de)activated by GetOptions (useCache).

If required, the cache can also be disabled globally by HateoasConfiguration.cache.enabled. In this case, the caching is deactivated - even if GetOptions.useCache = true is set.

If you now want to develop an application that executes all calls without caching by default and only one specific call with caching, then useCache: false must be set in all calls.

Feature request:
Introduced a possibility to set the default value for GetOptions.useCache. Completely independently, however, there should still be the option of hard deactivating the cache for all methods via the HateoasConfiguration.

**Comment by lagoshny** [comment]
@K-e-l-v-i-n-12 ,

In versions `3.3.4` and `2.6.4` added support to specify cache mode. Now you can use configuration like this: 

````ts
    hateoasConfig.configure({
      ....
      cache: {
        enabled: true,
        mode: CacheMode.ON_DEMAND
      }
    });
````
After that, only in methods that you have passed `useCache=true` will be use cache, other methods will not use cache.

Available two modes: `ALWAYS` it is by default and `ON_DEMAND`. Read more about it [here](https://github.com/lagoshny/ngx-hateoas-client#cache-params).
