### ISSUE TITLE
getResourceNameFromUrl failing to retrieve resourcename

### ISSUE THREAD

**Issue by ed4becky** [lagoshny/ngx-hateoas-client#81]
I am using the latest version of the library, and have found that the class returned from getResource is never correct. I have pinned it to the following:
I have a default route configured: https://gateway.sandbox.netfoundry.io/core/v2/
I access the resource at https://gateway.sandbox.netfoundry.io/core/v2/networks
My resource name is configured  as @HateoasResource('networks')

When the getResourceNameFromUrl  is called it tries to execute this statement (line 593):
`            return url.toLowerCase().replace(`${resourceRoute.rootUrl}/`, '').split('/')[0];`

That call returns "https:" which of course is not an entity so the result is a lagoshny-ngx-hateoas-client.mjs:123 
_"Not found resource type when create resource: 'https:'"_

**This issue is masked by the fact that in MOST cases the default Resource type will work.**  However in my case, extra methods are defined in my resource, which are "not found" downline because the basic resource type was created from the payload instead of the **real** resource class.

The issue is with the replace, which has a couple of issues:
1) there is no opening slash, for example` replace(`/${resourceRoute.rootUrl}/`, '')` vs `replace(`${resourceRoute.rootUrl}/`, '') `which results in the replace interpreting the first slash in resourceRoute.rootURL (https:/..) as the opening slash

2) the forward slashes in resourceRoute.rootUrl are not escaped in the replace call.  This may not be an issue if #1 is resolved.

I am surprised this issue hasn't come up before, but probably because most folk don't add additional methods to their resource classes?

**Comment by ed4becky** [comment]
![image](https://user-images.githubusercontent.com/2965767/196213445-56940c08-770d-4441-b8b8-e669f4aaca30.png)

**Comment by ed4becky** [comment]
Some additional information:
while the current test suite passes, if you change the root url in the tests from http to https, they fail - so the issue occurs with an https configured route

**Comment by lagoshny** [comment]
Hi @ed4becky, thank you for the good explanation of a problem,

In this case problem with root URL, that it ends with slash: https://gateway.sandbox.netfoundry.io/core/v2/ 
And `getResourceNameFromUrl` puts his own slash (it thinks that `rootUrl` ends without slash) and in summary we have double slash in code:

````ts
'https://gateway.sandbox.netfoundry.io/core/v2/networks'.replace('https://gateway.sandbox.netfoundry.io/core/v2//'); // => https
````

With `rootUrl` without slash on the end:

````ts
'https://gateway.sandbox.netfoundry.io/core/v2/networks'.replace('https://gateway.sandbox.netfoundry.io/core/v2/'); // => networks
````

I think it is good to handle both cases, I will add support for `rootUrl` that ended with slash.

**Comment by lagoshny** [comment]
Added support for both format of `rootUrl`, try it in new version `3.3.5`.
