### ISSUE TITLE
Empty Paged Collection request fails on "You try to get wrong resource type: expected PagedResourceCollection type"

### ISSUE THREAD

**Issue by ed4becky** [lagoshny/ngx-hateoas-client#83]
I am making a request for a PagedResouurce (networks).  When the results are empty, I get the error in the title, because the results are returned without an _embedded field
```
{
    "_links": {
        "self": {
            "href": "https://gateway.sandbox.netfoundry.io/core/v2/networks?page=0&size=30"
        }
    },
    "page": {
        "size": 0,
        "totalElements": 0,
        "totalPages": 1,
        "number": 0
    }
}
```

Since the results are empty and _embedde3d is OPTIONAl, is this the correct behavior?

function isPagedResourceCollection(object) {
    const baseCondition = isObject(object) &&
        ('_links' in object) &&
        ('page' in object);
    if (!baseCondition) {
        return false;
    }
    if (LibConfig.getConfig().halFormat.collections.embeddedOptional) {
        return baseCondition && (Object.keys(object).length === 2 ||
            '_embedded' in object && Object.keys(object).length === 3);
    }
    else {
        **return baseCondition && '_embedded' in object && Object.keys(object).length === 3;**
    }
}
```

**Comment by lagoshny** [comment]
@ed4becky look at the same [issue](https://github.com/lagoshny/ngx-hateoas-client/issues/66).

You can configure lib to ignore an empty _embedded props.

**Comment by ed4becky** [comment]
Thanks, sorry I missed that
