### ISSUE TITLE
Verbose Log is always on if isProduction is true

### ISSUE THREAD

**Issue by Flexns** [lagoshny/ngx-hateoas-client#90]
It seems there is currently no way to disable all logging. If I set isProduction to `true` to disable loglevel warn and error, info logs are always displayed, regardless of the setting of verboseLogs.

```
class ConsoleLogger {
   static info(message, ...optionalParams) {
        if (!LibConfig.getConfig().logs.verboseLogs && !LibConfig.getConfig().isProduction) // always returns false if isProduction == true
        { 
            return;
        }
        console.info(message, ...optionalParams);
    }
}

**Comment by lagoshny** [comment]
Hi @Flexns,
Thank you for the issue. Fixed it in `3.3.7` version.
