### ISSUE TITLE
getRelatedPage ignores sort option

### ISSUE THREAD

**Issue by ed4becky** [lagoshny/ngx-hateoas-client#92]
sort paramaters are not being sent when I call getRelatedPage on a resource.

I have tried with
    {
      pageParams: {size, page, sort: {name: "ASC"}},
      headers: {accept: 'application/hal+json'},
    }

and with
    {
      pageParams: {size, page},
      sort: {name: "ASC"},
      headers: {accept: 'application/hal+json'},
    }

The first just ignores the sort option.
The second one gets a type error, even though PagedGetOption extends GetOption, which includes sort: Sort

**Comment by lagoshny** [comment]
Hi @ed4becky ,
Yes it can be if you have a templated link and when template doesn't contain sort param then it ignored.
Because for templated links, we are trying to match params object to template placeholders.

I changed some logic for sort params, now it always added as HTTP request params for templated links too.
Try it in new version `3.3.8`.

**Comment by ed4becky** [comment]
still no sort.  I think the change needs to be made in  fillDefaultPageDataIfNoPresent

**Comment by ed4becky** [comment]
I have a simpler use case.  The issue is happening on a getPage call.  Tracing thru the code, 

I recorded a video: https://www.dropbox.com/s/zhpf1d8edd4mfti/2023-02-01_08-47-14.mp4?dl=0

**Comment by lagoshny** [comment]
@ed4becky thank you for the video!
In the video, you pass `sort` option in `pageParams` object, but you need to pass it separately like this:

````ts
{
      params: {
        testParam: 'test'
      },
      sort: {
        propertyName: 'ASC'
      },
      pageParams: {
        page: 1,
        size: 0
      }
````

You can see this [test case](https://github.com/lagoshny/ngx-hateoas-client/blob/master/projects/ngx-hateoas-client/src/lib/util/url.utils.spec.ts#L109).

If after that you have problem again please show it on video. The important moment of code is:

```ts
    if (!isEmpty(options.sort)) {
      resultParams = UrlUtils.generateSortParams(options.sort, resultParams);
    }
```

Please, then show on the video current value of `options.sort`.

**Comment by lagoshny** [comment]
Closed the issue due inactivity.
